# coding: utf-8

"""
    Adzerk Decision API

    Adzerk Decision API  # noqa: E501

    The version of the OpenAPI document: 1.0
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest

import adzerk_decision_sdk
from adzerk_decision_sdk.api.decision_api import DecisionApi  # noqa: E501
from adzerk_decision_sdk.rest import ApiException


class TestDecisionApi(unittest.TestCase):
    """DecisionApi unit test stubs"""

    def setUp(self):
        self.api = adzerk_decision_sdk.api.decision_api.DecisionApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_get_decisions(self):
        """Test case for get_decisions

        """
        pass


if __name__ == '__main__':
    unittest.main()
