# coding: utf-8

"""
    Adzerk Decision API

    Adzerk Decision API  # noqa: E501

    The version of the OpenAPI document: 1.0
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest

import adzerk_decision_sdk
from adzerk_decision_sdk.models.decision import Decision  # noqa: E501
from adzerk_decision_sdk.rest import ApiException


class TestDecision(unittest.TestCase):
    """Decision unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testDecision(self):
        """Test Decision"""
        # FIXME: construct object with mandatory attributes with example values
        # model = adzerk_decision_sdk.models.decision.Decision()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
