# coding: utf-8

"""
    Adzerk Decision API

    Adzerk Decision API  # noqa: E501

    The version of the OpenAPI document: 1.0
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest

import adzerk_decision_sdk
from adzerk_decision_sdk.models.consent import Consent  # noqa: E501
from adzerk_decision_sdk.rest import ApiException


class TestConsent(unittest.TestCase):
    """Consent unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testConsent(self):
        """Test Consent"""
        # FIXME: construct object with mandatory attributes with example values
        # model = adzerk_decision_sdk.models.consent.Consent()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
