"""
    Adzerk Decision API

    Adzerk Decision API  # noqa: E501

    The version of the OpenAPI document: 1.0
    Generated by: https://openapi-generator.tech
"""


import re  # noqa: F401
import sys  # noqa: F401

from adzerk_decision_sdk.model_utils import (  # noqa: F401
    ApiTypeError,
    ModelComposed,
    ModelNormal,
    ModelSimple,
    cached_property,
    change_keys_js_to_python,
    convert_js_args_to_python_args,
    date,
    datetime,
    file_type,
    none_type,
    validate_get_composed_info,
)

def lazy_import():
    from adzerk_decision_sdk.model.placement import Placement
    from adzerk_decision_sdk.model.user import User
    globals()['Placement'] = Placement
    globals()['User'] = User


class DecisionRequest(ModelNormal):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.

    Attributes:
      allowed_values (dict): The key is the tuple path to the attribute
          and the for var_name this is (var_name,). The value is a dict
          with a capitalized key describing the allowed value and an allowed
          value. These dicts store the allowed enum values.
      attribute_map (dict): The key is attribute name
          and the value is json key in definition.
      discriminator_value_class_map (dict): A dict to go from the discriminator
          variable value to the discriminator class name.
      validations (dict): The key is the tuple path to the attribute
          and the for var_name this is (var_name,). The value is a dict
          that stores validations for max_length, min_length, max_items,
          min_items, exclusive_maximum, inclusive_maximum, exclusive_minimum,
          inclusive_minimum, and regex.
      additional_properties_type (tuple): A tuple of classes accepted
          as additional properties values.
    """

    allowed_values = {
    }

    validations = {
    }

    additional_properties_type = None

    _nullable = False

    @cached_property
    def openapi_types():
        """
        This must be a method because a model may have properties that are
        of type self, this must run after the class is loaded

        Returns
            openapi_types (dict): The key is attribute name
                and the value is attribute type.
        """
        lazy_import()
        return {
            'placements': ([Placement],),  # noqa: E501
            'user': (User,),  # noqa: E501
            'keywords': ([str], none_type,),  # noqa: E501
            'url': (str, none_type,),  # noqa: E501
            'referrer': (str, none_type,),  # noqa: E501
            'ip': (str, none_type,),  # noqa: E501
            'blocked_creatives': ([int], none_type,),  # noqa: E501
            'is_mobile': (bool, none_type,),  # noqa: E501
            'include_pricing_data': (bool, none_type,),  # noqa: E501
            'notrack': (bool, none_type,),  # noqa: E501
            'enable_bot_filtering': (bool, none_type,),  # noqa: E501
            'enable_user_dbip': (bool, none_type,),  # noqa: E501
            'consent': ({str: (bool, date, datetime, dict, float, int, list, str, none_type)}, none_type,),  # noqa: E501
            'device_id': (str, none_type,),  # noqa: E501
            'parallel': (bool, none_type,),  # noqa: E501
            'intended_latitude': (float, none_type,),  # noqa: E501
            'intended_longitude': (float, none_type,),  # noqa: E501
            'radius': (float, none_type,),  # noqa: E501
            'include_matched_points': (bool, none_type,),  # noqa: E501
        }

    @cached_property
    def discriminator():
        return None


    attribute_map = {
        'placements': 'placements',  # noqa: E501
        'user': 'user',  # noqa: E501
        'keywords': 'keywords',  # noqa: E501
        'url': 'url',  # noqa: E501
        'referrer': 'referrer',  # noqa: E501
        'ip': 'ip',  # noqa: E501
        'blocked_creatives': 'blockedCreatives',  # noqa: E501
        'is_mobile': 'isMobile',  # noqa: E501
        'include_pricing_data': 'includePricingData',  # noqa: E501
        'notrack': 'notrack',  # noqa: E501
        'enable_bot_filtering': 'enableBotFiltering',  # noqa: E501
        'enable_user_dbip': 'enableUserDBIP',  # noqa: E501
        'consent': 'consent',  # noqa: E501
        'device_id': 'deviceID',  # noqa: E501
        'parallel': 'parallel',  # noqa: E501
        'intended_latitude': 'intendedLatitude',  # noqa: E501
        'intended_longitude': 'intendedLongitude',  # noqa: E501
        'radius': 'radius',  # noqa: E501
        'include_matched_points': 'includeMatchedPoints',  # noqa: E501
    }

    _composed_schemas = {}

    required_properties = set([
        '_data_store',
        '_check_type',
        '_spec_property_naming',
        '_path_to_item',
        '_configuration',
        '_visited_composed_classes',
    ])

    @convert_js_args_to_python_args
    def __init__(self, placements, *args, **kwargs):  # noqa: E501
        """DecisionRequest - a model defined in OpenAPI

        Args:
            placements ([Placement]): One or more Placement objects

        Keyword Args:
            _check_type (bool): if True, values for parameters in openapi_types
                                will be type checked and a TypeError will be
                                raised if the wrong type is input.
                                Defaults to True
            _path_to_item (tuple/list): This is a list of keys or values to
                                drill down to the model in received_data
                                when deserializing a response
            _spec_property_naming (bool): True if the variable names in the input data
                                are serialized names, as specified in the OpenAPI document.
                                False if the variable names in the input data
                                are pythonic names, e.g. snake case (default)
            _configuration (Configuration): the instance to use when
                                deserializing a file_type parameter.
                                If passed, type conversion is attempted
                                If omitted no type conversion is done.
            _visited_composed_classes (tuple): This stores a tuple of
                                classes that we have traveled through so that
                                if we see that class again we will not use its
                                discriminator again.
                                When traveling through a discriminator, the
                                composed schema that is
                                is traveled through is added to this set.
                                For example if Animal has a discriminator
                                petType and we pass in "Dog", and the class Dog
                                allOf includes Animal, we move through Animal
                                once using the discriminator, and pick Dog.
                                Then in Dog, we will make an instance of the
                                Animal class but this time we won't travel
                                through its discriminator because we passed in
                                _visited_composed_classes = (Animal,)
            user (User): [optional]  # noqa: E501
            keywords ([str], none_type): Keywords for keyword Targeting. Such as `\"keywords\": [\"foo\", \"bar\", \"baz\"]`.. [optional]  # noqa: E501
            url (str, none_type): The current page URL. [optional]  # noqa: E501
            referrer (str, none_type): The referrer URL. [optional]  # noqa: E501
            ip (str, none_type): The IP address. Required for [Geo-Targeting](https://dev.adzerk.com/docs/geo-location). [optional]  # noqa: E501
            blocked_creatives ([int], none_type): Numeric creative ids to disregard for ad selection. [optional]  # noqa: E501
            is_mobile (bool, none_type): If true, only ads containing a single image will be returned. [optional]  # noqa: E501
            include_pricing_data (bool, none_type): If true, return pricing data for the decision in the response. [optional]  # noqa: E501
            notrack (bool, none_type): If true, only return ads that are set to honor Do Not Track. [optional]  # noqa: E501
            enable_bot_filtering (bool, none_type): If making a client-side request, set to true. Defaults to false to ensure a server isn't seen as a bot. See [here](https://dev.adzerk.com/docs/tracking-overview#section-bot-filtering) for more info. [optional]  # noqa: E501
            enable_user_dbip (bool, none_type): If true, override the IP address of the request with the IP address supplied on the UserKey. If no IP address is found on the UserKey, this will fall back to the IP address on the request. Requires UserDB. [optional]  # noqa: E501
            consent ({str: (bool, date, datetime, dict, float, int, list, str, none_type)}, none_type): Object that sets the data consent preferences. Other consent settings are available in the GDPR settings documentation.. [optional]  # noqa: E501
            device_id (str, none_type): RTB requests only - sets an Identifier for Advertisers (IFA or IDFA). [optional]  # noqa: E501
            parallel (bool, none_type): [optional]  # noqa: E501
            intended_latitude (float, none_type): [optional]  # noqa: E501
            intended_longitude (float, none_type): [optional]  # noqa: E501
            radius (float, none_type): [optional]  # noqa: E501
            include_matched_points (bool, none_type): [optional]  # noqa: E501
        """

        _check_type = kwargs.pop('_check_type', True)
        _spec_property_naming = kwargs.pop('_spec_property_naming', False)
        _path_to_item = kwargs.pop('_path_to_item', ())
        _configuration = kwargs.pop('_configuration', None)
        _visited_composed_classes = kwargs.pop('_visited_composed_classes', ())

        if args:
            raise ApiTypeError(
                "Invalid positional arguments=%s passed to %s. Remove those invalid positional arguments." % (
                    args,
                    self.__class__.__name__,
                ),
                path_to_item=_path_to_item,
                valid_classes=(self.__class__,),
            )

        self._data_store = {}
        self._check_type = _check_type
        self._spec_property_naming = _spec_property_naming
        self._path_to_item = _path_to_item
        self._configuration = _configuration
        self._visited_composed_classes = _visited_composed_classes + (self.__class__,)

        self.placements = placements
        for var_name, var_value in kwargs.items():
            if var_name not in self.attribute_map and \
                        self._configuration is not None and \
                        self._configuration.discard_unknown_keys and \
                        self.additional_properties_type is None:
                # discard variable.
                continue
            setattr(self, var_name, var_value)
