# coding: utf-8

"""
    Adzerk Decision API

    Adzerk Decision API  # noqa: E501

    The version of the OpenAPI document: 1.0
    Generated by: https://openapi-generator.tech
"""


import pprint
import re  # noqa: F401

import six

from adzerk_decision_sdk.configuration import Configuration


class Content(object):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    """
    Attributes:
      openapi_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    openapi_types = {
        'type': 'str',
        'template': 'str',
        'custom_template': 'str',
        'data': 'object',
        'body': 'str'
    }

    attribute_map = {
        'type': 'type',
        'template': 'template',
        'custom_template': 'customTemplate',
        'data': 'data',
        'body': 'body'
    }

    def __init__(self, type=None, template=None, custom_template=None, data=None, body=None, local_vars_configuration=None):  # noqa: E501
        """Content - a model defined in OpenAPI"""  # noqa: E501
        if local_vars_configuration is None:
            local_vars_configuration = Configuration()
        self.local_vars_configuration = local_vars_configuration

        self._type = None
        self._template = None
        self._custom_template = None
        self._data = None
        self._body = None
        self.discriminator = None

        if type is not None:
            self.type = type
        if template is not None:
            self.template = template
        if custom_template is not None:
            self.custom_template = custom_template
        if data is not None:
            self.data = data
        if body is not None:
            self.body = body

    @property
    def type(self):
        """Gets the type of this Content.  # noqa: E501


        :return: The type of this Content.  # noqa: E501
        :rtype: str
        """
        return self._type

    @type.setter
    def type(self, type):
        """Sets the type of this Content.


        :param type: The type of this Content.  # noqa: E501
        :type: str
        """

        self._type = type

    @property
    def template(self):
        """Gets the template of this Content.  # noqa: E501


        :return: The template of this Content.  # noqa: E501
        :rtype: str
        """
        return self._template

    @template.setter
    def template(self, template):
        """Sets the template of this Content.


        :param template: The template of this Content.  # noqa: E501
        :type: str
        """

        self._template = template

    @property
    def custom_template(self):
        """Gets the custom_template of this Content.  # noqa: E501


        :return: The custom_template of this Content.  # noqa: E501
        :rtype: str
        """
        return self._custom_template

    @custom_template.setter
    def custom_template(self, custom_template):
        """Sets the custom_template of this Content.


        :param custom_template: The custom_template of this Content.  # noqa: E501
        :type: str
        """

        self._custom_template = custom_template

    @property
    def data(self):
        """Gets the data of this Content.  # noqa: E501


        :return: The data of this Content.  # noqa: E501
        :rtype: object
        """
        return self._data

    @data.setter
    def data(self, data):
        """Sets the data of this Content.


        :param data: The data of this Content.  # noqa: E501
        :type: object
        """

        self._data = data

    @property
    def body(self):
        """Gets the body of this Content.  # noqa: E501


        :return: The body of this Content.  # noqa: E501
        :rtype: str
        """
        return self._body

    @body.setter
    def body(self, body):
        """Sets the body of this Content.


        :param body: The body of this Content.  # noqa: E501
        :type: str
        """

        self._body = body

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.openapi_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, Content):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, Content):
            return True

        return self.to_dict() != other.to_dict()
